# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
      env:
         OPENEXCHANGEAPITOKEN: ${{ secrets.OPENEXCHANGEAPITOKEN }}
         PORT: 3000
         IPHOSTAPPLICATION: 0.0.0.0
    - run: npm run coverage
      env:
         OPENEXCHANGEAPITOKEN: ${{ secrets.OPENEXCHANGEAPITOKEN }}
         PORT: 3000
         IPHOSTAPPLICATION: 0.0.0.0
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - run: npm i -g codecov && npm run coverage:report && codecov -t ${{ secrets.CODECOV_TOKEN }}
